# SMTP Configuration for LuxeGlow E-Commerce
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=sidti0110@gmail.com
mail.smtp.password=uaxs xkzp xkrc mvyn
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com
mail.smtp.starttls.required=true
mail.from=sidti0110@gmail.com
mail.admin.email=admin@luxeglow.com
